### ISSUE TITLE
Swagger UI显示不了

### ISSUE THREAD

**Issue by Jcanc** [aspnet/AspNetCore.Docs.zh-cn#130]
Swagger UI显示不出来，报下面的提示
No operations defined in spec!

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Swashbuckle 和 ASP.NET Core 入门](https://docs.microsoft.com/zh-cn/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/aspnet/Docs.zh-cn/blob/live/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by CeciAc** [comment]
你好，@Jcanc
我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？
顺祝商祺！
Microsoft DOCS 国际团队

**Comment by Jcanc** [comment]
> 你好，@ Jcanc
> 我们诚挚感谢你的评论，我们会努力改善你在docs.microsoft.com的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？
> 顺祝商祺！
> Microsoft DOCS国际团队

**Comment by Jcanc** [comment]
> 你好，@ Jcanc
> 我们诚挚感谢你的评论，我们会努力改善你在docs.microsoft.com的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？
> 顺祝商祺！
> Microsoft DOCS国际团队

不知是不是我没按要求做，现在Swagger UI 页面显示不出来，也没有“浏览”按钮。
