### ISSUE TITLE
找不到SwaggerDoc和Info

### ISSUE THREAD

**Issue by selway** [aspnet/AspNetCore.Docs.zh-cn#131]
版本：3.0-preview
我遇到了这个错误，但是这在2.1版本中是可用的。

![image](https://user-images.githubusercontent.com/6679547/57964283-510d6180-7965-11e9-847a-5e79fdc39770.png)

![image](https://user-images.githubusercontent.com/6679547/57964288-5cf92380-7965-11e9-8074-d9e77fdd1f51.png)

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Swashbuckle 和 ASP.NET Core 入门](https://docs.microsoft.com/zh-cn/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by CeciAc** [comment]
你好，@selway
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
