### ISSUE TITLE
"添加数据库连接字符串"省略了太多

### ISSUE THREAD

**Issue by yatyu** [aspnet/AspNetCore.Docs.zh-cn#134]
“添加数据库连接字符串”这一段让人看不懂无法继续操作下去，如果这是一个面向入门级别的教程我认为应该把所有步骤讲解的清楚一点！

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [在 ASP.NET Core 中向 Razor Pages 应用添加模型](https://docs.microsoft.com/zh-cn/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by CeciAc** [comment]
Issue moved to [aspnet/AspNetCore.Docs #12817](https://github.com/aspnet/AspNetCore.Docs/issues/12817) via [**ZenHub**](https://www.zenhub.com/)
