### ISSUE TITLE
Models/Movie.cs 代码报错

### ISSUE THREAD

**Issue by dengdasam** [aspnet/AspNetCore.Docs.zh-cn#139]
Display(Name = "Release Date")
Column(TypeName = "decimal(18, 2)")
两行代码报错；
修改后运行OK
[Display(Name = "Release Date")]
[Column(TypeName = "decimal(18, 2)")]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: f71b0095-5175-f2e8-1db2-a800e0f77ce2
* Version Independent ID: 6886d687-d6bf-2652-4583-5de7b7353e45
* Content: [在 ASP.NET Core 应用中更新生成的页面](https://docs.microsoft.com/zh-cn/aspnet/core/tutorials/razor-pages/da1?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/da1.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/tutorials/razor-pages/da1.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This is a system wide problem. that's tracked in #13143

这是一个系统问题。这是在＃13143中跟踪的

**Comment by CeciAc** [comment]
你好，@dengdasam 

非常感谢你的参与。我们的团队已评审你的反馈，此问题似乎已有记录。 

请查看问题 #13143。因此我们将关闭这一重复的问题。 


深深的祝福， 
Microsoft DOCS International Team
