### ISSUE TITLE
http://contoso.com/api/pets/2?DogsOnly=true  cannot linkaction GetbyID()!!

### ISSUE THREAD

**Issue by tahen2** [aspnet/AspNetCore.Docs.zh-cn#140]
在文章开头第一个例子中，http://contoso.com/api/pets/2?DogsOnly=true   这个路由无法查找 GetByID 的第一个参数，该参数是一个名为 id 的整数。至少路由的动作方法时pets怎么会查找getbyid方法呢？是不是有错误？
[在此处输入反馈]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e24f48f8-6c4d-ecda-6ce6-a7826d396e99
* Version Independent ID: 9c4af557-8d06-4c6c-ad2a-0dd234547563
* Content: [ASP.NET Core 中的模型绑定](https://docs.microsoft.com/zh-cn/aspnet/core/mvc/models/model-binding?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/models/model-binding.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/mvc/models/model-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by lichasu** [comment]
Issue moved to [aspnet/AspNetCore.Docs #13207](https://github.com/aspnet/AspNetCore.Docs/issues/13207) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lichasu** [comment]
你好，@tahen2

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/aspnet/AspNetCore.Docs/issues/13207。 

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team
