### ISSUE TITLE
怎么关闭日志

### ISSUE THREAD

**Issue by RoinBi** [aspnet/AspNetCore.Docs.zh-cn#141]
[在此处输入反馈]
![image](https://user-images.githubusercontent.com/26728164/60878977-599e5c00-a273-11e9-848b-81e0ef832a62.png)
怎么关闭日志？

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 881cef77-11ef-ac11-06d0-0996a1ccfa1b
* Version Independent ID: 3d356334-e672-7e8b-1fef-7944ebee99eb
* Content: [在 ASP.NET Core 中使用 IHttpClientFactory 发出 HTTP 请求](https://docs.microsoft.com/zh-cn/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/http-requests.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/fundamentals/http-requests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @stevejgordon
* Microsoft Alias: **scaddie**

**Comment by lichasu** [comment]
你好，@RoinBi，
我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？
顺祝商祺！
Microsoft DOCS 国际团队

**Comment by RoinBi** [comment]
再使用 IHttpClientFactory 发出 HTTP 请求 就会打印出很多日志
例如 下图
![image](https://user-images.githubusercontent.com/26728164/61342737-d639c780-a87d-11e9-94c6-d990df43b78e.png)
而我这些日志是不需要的，如何关闭这些日志的打印呢？

**Comment by CeciAc** [comment]
你好，@RoinBi，
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
