### ISSUE TITLE
自定义 API 文档 下面的 XML 注释节点是否未完成

### ISSUE THREAD

**Issue by RanlinChen** [aspnet/AspNetCore.Docs.zh-cn#144]
“NSwag入门” “自定义 API 文档” 下面的 “XML 注释” 节点的文档内容 是否未完成
我查看“Swashbuckle 入门” 下面对应的节点文档是完整的。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 2483813a-3c16-7ddd-3160-43e6843b55d4
* Version Independent ID: 25f7fb5b-92b0-a45b-57ab-fdceab571884
* Content: [NSwag 和 ASP.NET Core 入门](https://docs.microsoft.com/zh-cn/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/getting-started-with-NSwag.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/tutorials/getting-started-with-NSwag.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by imba-tjd** [comment]
什么叫做未完成呢？我看着好像有啊
![图片](https://user-images.githubusercontent.com/24759802/61524299-c8846d80-aa48-11e9-9868-ca408e5a2a24.png)

**Comment by srvbpigh** [comment]
Hello, @RanlinChen
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by RanlinChen** [comment]
> 
> 
> 什么叫做未完成呢？我看着好像有啊
> ![图片](https://user-images.githubusercontent.com/24759802/61524299-c8846d80-aa48-11e9-9868-ca408e5a2a24.png)

对比  Swashbuckle 入门 >>> XML注释    感觉内容似乎不完整。

**Comment by CeciAc** [comment]
Issue moved to [aspnet/AspNetCore #12373](https://github.com/aspnet/AspNetCore/issues/12373) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
你好，@RanlinChen

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/aspnet/AspNetCore/issues/12373

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team
