### ISSUE TITLE
[BindNever] 属性 只能应用于模型属性，不能应用于方法参数。 防止模型绑定设置模型的属性。严重警告没说。

### ISSUE THREAD

**Issue by 1257960069** [aspnet/AspNetCore.Docs.zh-cn#170]
如果客户端提交的是Json格式的数据，BindRequiredAttribute与BindNeverAttribute特性类就不会起任何作用，这是因为模型直接通过Json.Net反序列化来创建，MVC框架并不知道属性的值从何而来。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e24f48f8-6c4d-ecda-6ce6-a7826d396e99
* Version Independent ID: 9c4af557-8d06-4c6c-ad2a-0dd234547563
* Content: [ASP.NET Core 中的模型绑定](https://docs.microsoft.com/zh-cn/aspnet/core/mvc/models/model-binding?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/mvc/models/model-binding.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/mvc/models/model-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by srvbpigh** [comment]
Hello, @1257960069
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [aspnet/AspNetCore #12884](https://github.com/aspnet/AspNetCore/issues/12884) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
你好，@1257960069

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/aspnet/AspNetCore/issues/12884

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team
