### ISSUE TITLE
translate error

### ISSUE THREAD

**Issue by tai-yi** [aspnet/AspNetCore.Docs.zh-cn#186]
### en-us
Do use no-tracking queries in Entity Framework Core when accessing data for read-only purposes. EF Core can return the results of no-tracking queries more efficiently.
### zh-cn
不要使用无跟踪查询中 Entity Framework Core 用于只读目的访问数据时。 EF Core 可以更有效地返回非跟踪查询的结果。

It should be “使用 `no-tracking` 查询 在 Entity Framework Core 用于只读目的访问数据时。 EF Core 可以更有效地返回非跟踪查询的结果。"

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 9599d917-4e43-f1ae-452a-1f11aaa985ed
* Version Independent ID: 5cc05b6c-c671-3607-3217-7db73ebc1f28
* Content: [ASP.NET Core 的性能最佳实践](https://docs.microsoft.com/zh-cn/aspnet/core/performance/performance-best-practices?view=aspnetcore-2.2)
* Content Source: [aspnetcore/performance/performance-best-practices.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/performance/performance-best-practices.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @tai-yi
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @tai-yi 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-cn/aspnet/core/performance/performance-best-practices?view=aspnetcore-2.2

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
