### ISSUE TITLE
With applying the turiols steps by steps, an error still hanppen

### ISSUE THREAD

**Issue by ZGarry** [aspnet/AspNetCore.Docs.zh-cn#192]
![image](https://user-images.githubusercontent.com/43488431/64313331-e9dfef80-cfdd-11e9-8378-f0732c815d59.png)

An unhandled exception occurred while processing the request.
SqlException: Cannot open database "RazorPagesMovieContext-697bd573-26b3-4a29-bb64-3dbb2a78aa82" requested by the login. The login failed.
Login failed for user 'DESKTOP-MTNMLTC\admin'.
System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, object providerInfo, string newPassword, SecureString newSecurePassword, bool redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, bool applyTransientFaultHandling)

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [在 ASP.NET Core 中向 Razor Pages 应用添加模型](https://docs.microsoft.com/zh-cn/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @ZGarry
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
Recommend closing. The tutorial does work. This error is specifically mentioned.
