### ISSUE TITLE
中文版本代码也被翻译

### ISSUE THREAD

**Issue by defoliations** [aspnet/AspNetCore.Docs.zh-cn#197]
布尔值
字节、SByte
Char
DateTime
DateTimeOffset
小数
双精度
Enum
Guid
Int16、Int32、Int64
单精度
TimeSpan
UInt16、UInt32、UInt64
URI
Version

中文版本中，很多代码相关的信息被翻译，希望能改进，或者能参照Wiki一样接受社区编辑，共同完善文档内容

**Comment by srvbpigh** [comment]
Hello, @defoliations
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@defoliations
我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？
顺祝商祺！
Microsoft DOCS 国际团队

**Comment by defoliations** [comment]
> 你好，@defoliations
> 我们诚挚感谢你的评论，我们会努力改善你在docs.microsoft.com的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？
> 顺祝商祺！
> 微软DOCS国际团队

**Comment by defoliations** [comment]
https://docs.microsoft.com/zh-cn/aspnet/core/mvc/models/model-binding?view=aspnetcore-3.0#simple-types

在这个位置中，类似与bool，byte，double之类的关键字，被翻译成中文

**Comment by CeciAc** [comment]
你好，@<参与者的 GITHUB 名>  

感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/aspnet/core/mvc/models/model-binding?view=aspnetcore-3.0#simple-types

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 


深深的祝福， 

Microsoft DOCS International Team
