### ISSUE TITLE
中文版本文案错误

### ISSUE THREAD

**Issue by yomunsam** [aspnet/AspNetCore.Docs.zh-cn#201]
“组件的名称必须以大写字符开头。 例如， MyCoolComponent是有效的，并且MyCoolComponent无效。”

英文版本中第二个“MyCoolComponent”是“myCoolComponent”

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [创建和使用 ASP.NET Core Razor 组件](https://docs.microsoft.com/zh-cn/aspnet/core/blazor/components?view=aspnetcore-3.0#component-classes)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @yomunsam
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [aspnet/AspNetCore.Docs #14927](https://github.com/aspnet/AspNetCore.Docs/issues/14927) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
你好，@yomunsam

感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/aspnet/core/blazor/components?view=aspnetcore-3.0#component-classes

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 


深深的祝福， 

Microsoft DOCS International Team

**Comment by NaBian** [comment]
The problem still exists

**Comment by CeciAc** [comment]
你好，@NaBian

感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/aspnet/core/blazor/components?view=aspnetcore-3.0#component-classes

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 

深深的祝福， 

Microsoft DOCS International Team

**Comment by h82258652** [comment]
3.1版本又出现这个问题了
https://docs.microsoft.com/zh-cn/aspnet/core/blazor/components?view=aspnetcore-3.1&viewFallbackFrom=aspnetcore-3.0#component-classes
