### ISSUE TITLE
中文翻译错误

### ISSUE THREAD

**Issue by yomunsam** [aspnet/AspNetCore.Docs.zh-cn#202]
The `Router` component enables routing to each component with a specified route. 

中文翻译是：
@No__t-0 组件允许路由到具有指定路由的每个组件。 @No__t-0 组件将出现在app.config文件中：

这个 `@No__t-0 ` 看懵了

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 79da574a-570f-04eb-86bd-c8065a016f44
* Version Independent ID: ac771374-6102-b838-57d2-e99bcf3f7d3e
* Content: [ASP.NET Core Blazor 路由](https://docs.microsoft.com/zh-cn/aspnet/core/blazor/routing?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/routing.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/blazor/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @yomunsam
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@yomunsam

感谢你的反馈。 

我们的工程团队已评审并接受你的建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/aspnet/core/blazor/routing?view=aspnetcore-3.0  

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 

深深的祝福， 
Microsoft DOCS International Team
