### ISSUE TITLE
中文翻译错误 代码被翻译

### ISSUE THREAD

**Issue by yomunsam** [aspnet/AspNetCore.Docs.zh-cn#203]
中文位置：

## 从多个程序集中路由到组件

其中，中文文本

> < 路由器 AppAssembly = "typeof （程序）。程序集 "AdditionalAssemblies =" new [] {typeof （Component1）。Assembly} > ...

不应该翻译，应保留英文原文

> <Router AppAssembly="typeof(Program).Assembly" AdditionalAssemblies="new[] { typeof(Component1).Assembly }>

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 79da574a-570f-04eb-86bd-c8065a016f44
* Version Independent ID: ac771374-6102-b838-57d2-e99bcf3f7d3e
* Content: [ASP.NET Core Blazor 路由](https://docs.microsoft.com/zh-cn/aspnet/core/blazor/routing?view=aspnetcore-3.0#)
* Content Source: [aspnetcore/blazor/routing.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/blazor/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @yomunsam
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [aspnet/AspNetCore #14864](https://github.com/aspnet/AspNetCore/issues/14864) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
你好，@yomunsam

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 -https://github.com/aspnet/AspNetCore/issues/14864

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team
