### ISSUE TITLE
Linux下执行会导致项目无法运行

### ISSUE THREAD

**Issue by yatyu** [aspnet/AspNetCore.Docs.zh-cn#204]
在linux下执行
dotnet dev-certs https --clean
dotnet dev-certs https --trust
再运行项目会得到一个错误
crit: Microsoft.AspNetCore.Server.Kestrel [0]
       Unable to start kestrel 
在openSUSE和xUbuntu上都是一样的。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [强制实施 HTTPS 在 ASP.NET Core](https://docs.microsoft.com/zh-cn/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/security/enforcing-ssl.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @yatyu
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@yatyu
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
