### ISSUE TITLE
设定数据库种子(Seed the database) tag

### ISSUE THREAD

**Issue by 95** [aspnet/AspNetCore.Docs.zh-cn#207]
using MvcMovie.Data; //add

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: a0a4022c-7ef1-3c30-4f9d-cf521a57a44a
* Version Independent ID: a0b5e15c-d747-8710-95fb-a55c09861a1e
* Content: [在 ASP.NET Core MVC 应用中使用 SQL](https://docs.microsoft.com/zh-cn/aspnet/core/tutorials/first-mvc-app/working-with-sql?view=aspnetcore-3.0&tabs=visual-studio-code#seed-the-database)
* Content Source: [aspnetcore/tutorials/first-mvc-app/working-with-sql.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/tutorials/first-mvc-app/working-with-sql.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @95
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
你好，@95
我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？
顺祝商祺！
Microsoft DOCS 国际团队

**Comment by 95** [comment]
`using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Linq;
**using MvcMovie.Data; //add**

namespace MvcMovie.Models
{
    public static class SeedData
    {
        public static void Initialize(IServiceProvider serviceProvider)
        {
            using (var context = new **MvcMovieContext**(
                serviceProvider.GetRequiredService<
                    DbContextOptions<MvcMovieContext>>()))
            {
                // Look for any movies.
                if (context.Movie.Any())
                {
                    return;   // DB has been seeded
                }

                context.Movie.AddRange(
                    new Movie
                    {
                        Title = "When Harry Met Sally",
                        ReleaseDate = DateTime.Parse("1989-2-12"),
                        Genre = "Romantic Comedy",
                        Price = 7.99M
                    },

                    new Movie
                    {
                        Title = "Ghostbusters ",
                        ReleaseDate = DateTime.Parse("1984-3-13"),
                        Genre = "Comedy",
                        Price = 8.99M
                    },

                    new Movie
                    {
                        Title = "Ghostbusters 2",
                        ReleaseDate = DateTime.Parse("1986-2-23"),
                        Genre = "Comedy",
                        Price = 9.99M
                    },

                    new Movie
                    {
                        Title = "Rio Bravo",
                        ReleaseDate = DateTime.Parse("1959-4-15"),
                        Genre = "Western",
                        Price = 3.99M
                    }
                );
                context.SaveChanges();
            }
        }
    }
}`

**Comment by CeciAc** [comment]
你好，@95
我们正在跟进我们之前的评论。为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？
顺祝商祺！
Microsoft DOCS 国际团队

**Comment by 95** [comment]
> `using Microsoft.EntityFrameworkCore;
> using Microsoft.Extensions.DependencyInjection;
> using System;
> using System.Linq;
> **using MvcMovie.Data; //add**
> 
> namespace MvcMovie.Models
> {
> public static class SeedData
> {
> public static void Initialize(IServiceProvider serviceProvider)
> {
> using (var context = new **MvcMovieContext**(
> serviceProvider.GetRequiredService<
> DbContextOptions>()))
> {
> // Look for any movies.
> if (context.Movie.Any())
> {
> return; // DB has been seeded
> }
> 
> ```
>             context.Movie.AddRange(
>                 new Movie
>                 {
>                     Title = "When Harry Met Sally",
>                     ReleaseDate = DateTime.Parse("1989-2-12"),
>                     Genre = "Romantic Comedy",
>                     Price = 7.99M
>                 },
> 
>                 new Movie
>                 {
>                     Title = "Ghostbusters ",
>                     ReleaseDate = DateTime.Parse("1984-3-13"),
>                     Genre = "Comedy",
>                     Price = 8.99M
>                 },
> 
>                 new Movie
>                 {
>                     Title = "Ghostbusters 2",
>                     ReleaseDate = DateTime.Parse("1986-2-23"),
>                     Genre = "Comedy",
>                     Price = 9.99M
>                 },
> 
>                 new Movie
>                 {
>                     Title = "Rio Bravo",
>                     ReleaseDate = DateTime.Parse("1959-4-15"),
>                     Genre = "Western",
>                     Price = 3.99M
>                 }
>             );
>             context.SaveChanges();
>         }
>     }
> }
> ```
> 
> }`

highlight 部分就是我的回复呢，new MvcMovieContext (Using MvcMovie.Data)

**Comment by 95** [comment]
> 你好，@95
> 我们正在跟进我们之前的评论。为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？
> 顺祝商祺！
> Microsoft DOCS 国际团队

我看到现在已经有了！

**Comment by 95** [comment]
The current is fixed.
