### ISSUE TITLE
PMerr:ScriptHalted

### ISSUE THREAD

**Issue by sunmakets** [aspnet/AspNetCore.Docs.zh-cn#212]
Microsoft.EntityFrameworkCore.Tools 已安装

PMC 里面 不管怎么输入有关迁移的命令 都是ScriptHalted

这是什么原因呢？

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [将模型添加到 ASP.NET Core MVC 应用](https://docs.microsoft.com/zh-cn/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @sunmakets
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [aspnet/AspNetCore.Docs #15363](https://github.com/aspnet/AspNetCore.Docs/issues/15363) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
你好，@sunmakets

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 -  https://github.com/aspnet/AspNetCore.Docs/issues/15363

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team
