### ISSUE TITLE
文章中出现错别字

### ISSUE THREAD

**Issue by caolong373** [aspnet/AspNetCore.Docs.zh-cn#217]
标题：绑定源参数推理
非转【移】形式，应该翻译为：非转义形式

原文如下：
当值可能包含 %2f（即 /）时，请勿使用 [FromRoute]。 %2f 不会转换为 /（非转移形式）。 如果值可能包含 %2f，则使用 [FromQuery]。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b391017f-25e1-d5e1-c4f7-020408ade7b5
* Version Independent ID: 263a7b64-2e42-bbfc-c1d3-61680438e1e4
* Content: [使用 ASP.NET Core 创建 Web API](https://docs.microsoft.com/zh-cn/aspnet/core/web-api/?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/web-api/index.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/web-api/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by srvbpigh** [comment]
Hello, @caolong373
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@caolong373

非常感谢你的参与。我们的团队已评审你的反馈，此问题似乎已有记录。 

请查看问题 https://github.com/aspnet/AspNetCore.Docs.zh-cn/pull/218 。因此我们将关闭这一重复的问题。 


深深的祝福， 
Microsoft DOCS International Team
