### ISSUE TITLE
有一处错误

### ISSUE THREAD

**Issue by import1bones** [aspnet/AspNetCore.Docs.zh-cn#220]
在添加数据库上下文这一项中，Startup.cs中高亮的部分有错误，高亮的部分应是 
`services.AddDbContext<TodoContext>(opt =>
               opt.UseInMemoryDatabase("TodoList"));`
而不是`opt.UseInMemoryDatabase("TodoList"));
            services.AddControllers();`
使用的是Chrome浏览器

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [教程：使用 ASP.NET Core 创建 Web API](https://docs.microsoft.com/zh-cn/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by imba-tjd** [comment]
我的就是这样啊

![图片](https://user-images.githubusercontent.com/24759802/69491422-f9c9ea00-0ecf-11ea-9ea2-e4787e9b30b0.png)

**Comment by import1bones** [comment]
看不了你的图片哦，[https://docs.microsoft.com/zh-cn/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.0&tabs=visual-studio#feedback](url)，在这个网页中是错误的

**Comment by import1bones** [comment]
@imba-tjd 但是我发的那个网址里面他这个位置还是错的啊，
![批注 2019-11-24 152902](https://user-images.githubusercontent.com/12779972/69491501-23374580-0ed1-11ea-86af-57cf857447ad.png)

**Comment by import1bones** [comment]
我的这个版本是.net core3.0 ,是不是我们的版本不一致啊。

**Comment by imba-tjd** [comment]
确实有问题。FF和Edge是正常显示的，Cent(Chromium)和Edge Chromium的显示是错的。

**Comment by srvbpigh** [comment]
Hello, @import1bones
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
The code is correct. Recommend closing this issue.

**Comment by imba-tjd** [comment]
@Rick-Anderson Chrome doesn't properly display it.

**Comment by Rick-Anderson** [comment]
Chrome has problems with highlighting at 100%. Try 80% magnification.

Recommend close issue.

**Comment by import1bones** [comment]
@Rick-Anderson  would you like to add a tip to show this page need 80% magnification?
because this page was used to teach beginner,wrong highlight have misleading.

**Comment by v-maudel** [comment]
Issue moved to [aspnet/AspNetCore.Docs #15858](https://github.com/aspnet/AspNetCore.Docs/issues/15858) via [**ZenHub**](https://www.zenhub.com/)
