### ISSUE TITLE
why audio oncanPlay No response? and how get audioPlayer duration

### ISSUE THREAD

**Issue by 19chang19** [aspnet/AspNetCore.Docs.zh-cn#221]
[在此处输入反馈]
<audio @ref="audioPlayer" src="@AudioSrc" @oncanplay="oncanPlay">@ChildContent</audio>

1.why oncanPlay No response?
2.how get audioPlayer duration?
---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [ASP.NET Core Blazor 入门](https://docs.microsoft.com/zh-cn/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @19chang19
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by 19chang19** [comment]
<audio @ref="audioPlayer" src="@AudioSrc" oncanplay='audio_player.updataTimejs(this,@DotNetObjectReference.Create(this))'>@ChildContent</audio>


and error    Uncaught SyntaxError: Unexpected end of input

i see html is 
oncanplay="audio_player.updataTimejs(this,Microsoft.JSInterop.DotNetObjectReference`1[WebCore.Shared.AudioPlayer])"

**Comment by CeciAc** [comment]
Issue moved to [aspnet/AspNetCore #17526](https://github.com/aspnet/AspNetCore/issues/17526) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @19chang19

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/aspnet/AspNetCore/issues/17526

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
