### ISSUE TITLE
注册数据库上下文引用错误

### ISSUE THREAD

**Issue by skiingwang** [aspnet/AspNetCore.Docs.zh-cn#223]
在startup.cs中应当引用的是Data:
// RazorPagesMovieContext was be defined in Data.RazorPagesMovieContext.cs
using using RazorPagesMovie.Data;

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [在 ASP.NET Core 中向 Razor Pages 应用添加模型](https://docs.microsoft.com/zh-cn/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @skiingwang
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [aspnet/AspNetCore.Docs #16055](https://github.com/aspnet/AspNetCore.Docs/issues/16055) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
你好，@skiingwang 

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/aspnet/AspNetCore.Docs/issues/16055

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team
