### ISSUE TITLE
重写配置节 linux Centos7   上不起作用 

### ISSUE THREAD

**Issue by AKA285066112** [aspnet/AspNetCore.Docs.zh-cn#224]
[https://docs.microsoft.com/zh-cn/aspnet/core/fundamentals/host/web-host?view=aspnetcore-3.1](https://docs.microsoft.com/zh-cn/aspnet/core/fundamentals/host/web-host?view=aspnetcore-3.1)
#@Override configuration

**config Settings did not work        on linux CentOS7**

`var config = new ConfigurationBuilder()
            .SetBasePath(Directory.GetCurrentDirectory())
            .AddJsonFile("hostsettings.json", optional: true)
            .AddCommandLine(args)
            .Build();

          Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =&gt; 
                {
                    webBuilder.UseConfiguration(config)
                    .UseStartup&lt;Startup&gt;(); 
                });
`
hostsettings.json
{
  "urls": "https://127.0.0.1:5011;http://127.0.0.1:5010"
}

Still using port 5000, 5001
~# dotnet /home/OpenAPI-5010/WebAPI.dll
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
System.IO.IOException: Failed to bind to address http://127.0.0.1:5000: address already in use.
 ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use
 ---> System.Net.Sockets.SocketException (98): Address already in use

**Comment by srvbpigh** [comment]
Hello, @AKA285066112
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by AKA285066112** [comment]
当配置成  systemctl     *.service  运行得得时候时 好的  OK 
`~# systemctl start  openapi5010.service
~# systemctl status  openapi5010.service`

● openapi5010.service - OpenAPI5010
   Loaded: loaded (/etc/systemd/system/openapi5010.service; enabled; vendor preset: disabled)
   Active: active (running) since 三 2019-12-11 15:40:59 CST; 9s ago
 Main PID: 5385 (dotnet)
   CGroup: /system.slice/openapi5010.service
           └─5385 /usr/bin/dotnet /home/OpenAPI-5010/WebAPI.dll

dotnet[5385]: info: Microsoft.Hosting.Lifetime[0]
dotnet[5385]: Now listening on: https://127.0.0.1:5011
dotnet[5385]: info: Microsoft.Hosting.Lifetime[0]
dotnet[5385]: Now listening on: http://127.0.0.1:5010
