### ISSUE TITLE
无法直接将json内容注入静态属性

### ISSUE THREAD

**Issue by 1257960069** [aspnet/AspNetCore.Docs.zh-cn#225]
如果类MyOptions的Option1 属性是静态属性,我想在使用services.Configure&lt;MyOptions&gt;() 方法后直接通过属性的静态类 MyOptions.Option1 来进行取值,但是我尝试之后是MyOptions.Option1 的值是null

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [ASP.NET Core 中的选项模式](https://docs.microsoft.com/zh-cn/aspnet/core/fundamentals/configuration/options?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @1257960069
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [aspnet/AspNetCore.Docs #16226](https://github.com/aspnet/AspNetCore.Docs/issues/16226) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
你好，@1257960069 

非常感谢你的参与。你的反馈与原始文档有关。  

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/aspnet/AspNetCore.Docs/issues/16226。  

非常感谢你对我们的文章作出的贡献。   

深深的祝福，  
Microsoft DOCS International Team
