### ISSUE TITLE
How to get the IP address of the docker host

### ISSUE THREAD

**Issue by lovachen** [aspnet/AspNetCore.Docs.zh-cn#231]
[在此处输入反馈]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 3a7ec3c3-918c-6ffd-1ac0-4f88b89d9295
* Version Independent ID: 1c1f72f1-3d5d-3397-c17d-1889dbae6fee
* Content: [通过 .NET 客户端调用 gRPC 服务](https://docs.microsoft.com/zh-cn/aspnet/core/grpc/client?view=aspnetcore-3.0)
* Content Source: [aspnetcore/grpc/client.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/grpc/client.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by srvbpigh** [comment]
Hello, @lovachen
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @lovachen 

Your contribution is much appreciated. Yet, this feedback is related with product, please kindly log by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles.
	
Kind regards,
Microsoft DOCS International Team
