### ISSUE TITLE
生成的pdf有很多重复内容

### ISSUE THREAD

**Issue by yunfeiyang1916** [aspnet/AspNetCore.Docs.zh-cn#234]
生成的pdf有很多重复内容

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: ad8c13e7-78e6-cf9a-e7cb-3215df5fd1c4
* Version Independent ID: a3c1d2a6-625a-3409-120d-8372230a8196
* Content: [ASP.NET Core 简介](https://docs.microsoft.com/zh-cn/aspnet/core/?view=aspnetcore-3.0)
* Content Source: [aspnetcore/index.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @yunfeiyang1916
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@yunfeiyang1916
我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？
顺祝商祺！
Microsoft DOCS 国际团队

**Comment by yunfeiyang1916** [comment]
@CeciAc ，你好。
在https://docs.microsoft.com/zh-cn/aspnet/core/?view=aspnetcore-3.1页面下方提供了“下载PDF”功能，下载后的pdf有很多重复内容，比如在教程=>MVC->添加控制器章节，第150页-154页，与155页-159页完全重复了。也就是有许多章节内容重复了两次。

**Comment by Rick-Anderson** [comment]
google translate as @CeciAc, hello.
The "Download PDF" function is provided at the bottom of the page at https://docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-3.1. The downloaded pdf has a lot of duplicate content, such as in the tutorial => MVC -> Add controller chapters, pages 150-154, completely duplicate pages 155-159. That is, many chapters are repeated twice.

I think that's expected and a problem with the 3 tabs:
Visual Studio
Visual Studio Code
Visual Studio for Mac

If you compare the PDF with [Get started with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-3.1&tabs=visual-studio) you get duplicate content for VS, VS Code, VS Mac. The PDF is also showing some 2.2 content. I believe it should only show 3.1 content.

The following is 2.2 content in the PDF.
![image](https://user-images.githubusercontent.com/3605364/71569022-0eba1000-2a70-11ea-92bc-5f9370220564.png)


I suppose you're expected to click on one tab and skip the other content.

@CeciAc  this should be translated and moved to https://github.com/MicrosoftDocs/feedback

**Comment by CeciAc** [comment]
你好，@yunfeiyang1916

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/feedback/issues/2345

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
你好，@yunfeiyang1916 

非常感谢你的参与。你的反馈与原始文档有关。  

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/feedback/issues/2345。  

非常感谢你对我们的文章作出的贡献。   

深深的祝福，  
Microsoft DOCS International Team
