### ISSUE TITLE
可重用的 UI依赖于MVC

### ISSUE THREAD

**Issue by qinqoushui** [aspnet/AspNetCore.Docs.zh-cn#236]
在CORE3.1中，默认使用UseEndpoints，将导致Razor 类库不能正常工作。需要禁用UseEndpoints并重新启用MVC。
 services.AddMvc(r=&gt;r.EnableEndpointRouting=false);

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 9fd019c7-ceb7-6ef3-26ba-6b44341b6fc5
* Version Independent ID: fd116d00-0dc7-efaf-c714-34d77b345a05
* Content: [ASP.NET Core 的类库中的可重用 Razor UI](https://docs.microsoft.com/zh-cn/aspnet/core/razor-pages/ui-class?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/ui-class.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/razor-pages/ui-class.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @qinqoushui
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [aspnet/AspNetCore.Docs #16527](https://github.com/aspnet/AspNetCore.Docs/issues/16527) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
你好，@qinqoushui 

非常感谢你的参与。你的反馈与原始文档有关。  

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/aspnet/AspNetCore.Docs/issues/16527。  

非常感谢你对我们的文章作出的贡献。   

深深的祝福，  
Microsoft DOCS International Team
