### ISSUE TITLE
中文版本文案错误

### ISSUE THREAD

**Issue by tonyonder** [aspnet/AspNetCore.Docs.zh-cn#237]
"AspNetCore.Blazor。DataAnnotations是使用 DataAnnotationsValidator 组件填充验证体验缺口的包。 包当前正在试验。"和“AspNetCore.Blazor。DataAnnotations 实验包引入了一个附加的验证特性 ComparePropertyAttribute，该特性围绕这些限制。”这里面“AspNetCore.Blazor。DataAnnotations”符号有问题，看起来怪怪的。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: eef47457-c8cf-74a4-b884-c1fe5c2ef52d
* Version Independent ID: 09a02d10-2834-467d-d8c2-3fd19ceb3863
* Content: [ASP.NET Core Blazor 窗体和验证](https://docs.microsoft.com/zh-cn/aspnet/core/blazor/forms-validation?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/forms-validation.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/blazor/forms-validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @tonyonder
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@tonyonder

感谢你的发布内容。

当前不接受有关机器翻译内容的翻译问题的发布内容。

我们重视你对人工翻译内容（用于训练机器翻译引擎）的反馈和建议，你的参与将逐渐提高人工翻译和机器翻译的质量。

人工翻译主题可以通过每个内容文件标题中的 ms.translationtype 元数据值“HT”与机器翻译主题（使用“MT”作为元数据值）区别开。

非常感谢你的支持。

Microsoft DOCS 全球体验团队
