### ISSUE TITLE
中文翻译错误

### ISSUE THREAD

**Issue by tonyonder** [aspnet/AspNetCore.Docs.zh-cn#238]
“使用泛型类型并返回值时，请使用ValueTask&lt;t &gt;：”这里应该是：“ValueTask&lt;T&gt;”。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 49807900-0d56-e23c-1aef-d79099caeffb
* Version Independent ID: feff434f-912c-0985-d575-4a23a629057d
* Content: [ASP.NET Core Blazor JavaScript 互操作](https://docs.microsoft.com/zh-cn/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/javascript-interop.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/blazor/javascript-interop.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @tonyonder
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@tonyonder

感谢你的发布内容。

当前不接受有关机器翻译内容的翻译问题的发布内容。

我们重视你对人工翻译内容（用于训练机器翻译引擎）的反馈和建议，你的参与将逐渐提高人工翻译和机器翻译的质量。

人工翻译主题可以通过每个内容文件标题中的 ms.translationtype 元数据值“HT”与机器翻译主题（使用“MT”作为元数据值）区别开。

非常感谢你的支持。

Microsoft DOCS 全球体验团队
