### ISSUE TITLE
Kestrel 默认只支持Get和Post

### ISSUE THREAD

**Issue by dotnba** [aspnet/AspNetCore.Docs.zh-cn#241]
怎么支持Put/Delete等其他Http方法

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: f22dcddb-0c25-be1a-9a02-9e71dce86bdb
* Version Independent ID: 3e0e12c2-e544-5655-e001-d2ec180b11a8
* Content: [ASP.NET Core 中的 Kestrel Web 服务器实现](https://docs.microsoft.com/zh-cn/aspnet/core/fundamentals/servers/kestrel?tabs=aspnetcore2x&view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/servers/kestrel.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/fundamentals/servers/kestrel.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @dotnba
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [aspnet/AspNetCore.Docs #16947](https://github.com/aspnet/AspNetCore.Docs/issues/16947) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
你好，@dotnba 

非常感谢你的参与。你的反馈与原始文档有关。  

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/aspnet/AspNetCore.Docs/issues/16947。  

非常感谢你对我们的文章作出的贡献。   

深深的祝福，  
Microsoft DOCS International Team
